### PR TITLE
[#50] contenthash and hot reload

### LINKED ISSUE #50: Cannot use [chunkhash] or [contenthash] for chunk
ERROR in chunk runtime [entry]
[name].[contenthash].js
Cannot use [chunkhash] or [contenthash] for chunk in '[name].[contenthash].js' (use [hash] instead)

image

### PR DESCRIPTION
**Pull request by jacekk**
Fixes #50 . Probably not the best solution, but seems to be working.

----

Additionally, added `babel-jest` into dev deps, as it is used by `jest`. Also, fixed one test check.

### CODE REVIEW

**Comment by jakoblind** [comment]
This is a good quick fix to this problem. Thanks for this PR! I guess the "correct" solution is to have separate dev and prod configs, but we don't currently have that. 

Two things:
1. This code should only be visible if both "React hot loader" and "Code split vendors" is selected. Currently, it's always visible.
2. Could we add a comment in the generated code describing why this piece of code is needed. Proposal: "Cannot use contenthash when hot reloading is enabled"

**Comment by jacekk** [comment]
> This is a good quick fix to this problem. Thanks for this PR! I guess the "correct" solution is to have separate dev and prod configs, but we don't currently have that.
> 
> Two things:
> 
> 1. This code should only be visible if both "React hot loader" and "Code split vendors" is selected. Currently, it's always visible.
> 2. Could we add a comment in the generated code describing why this piece of code is needed. Proposal: "Cannot use contenthash when hot reloading is enabled"

I wouldn't say separate configs are required because of a single condition. At least, I prefer to have one file.

* re 1) I will try to add.
* re 2) I will add.

**Comment by jacekk** [comment]
@jakoblind Refactored a bit. Additionally, added some tests related to the relevant bug. I had to improved `jest` config a bit, just to make those tests working. Please, review again.

BTW, some tests were skipped; so enabled in this very PR. Could not see why those were skipped :/

**Comment by jakoblind** [comment]
awesome! Yes, those test was probably out commented by mistake. thanks for adding them back in. One detail: If the user doesn't select anything he will still see an empty function exported:

image

For a newbie coming to webpack it's confusing. I propose to show the old `module.exports = config;` by default instead. What do you think?

**Comment by jacekk** [comment]
@jakoblind I was/am aware of that empty function, but I wanted to make it more future-proof; in case some additional logic would require access to `argv` or even `env`. I guess YAGNI applies here, but adding more and more unnecessary logic (export the config vs. export a function) makes less sense in this case. Now, the output of webpack file is consistent, and I prefer that.

Having said the above, what's the final step?

**Comment by jakoblind** [comment]
Usually, I would agree that consistency is a good guiding principle. However, the code we generate here is read by people who are new to webpack and are even a bit scared of the webpack config. That's why I think it's important to always show the simplest version of the webpack config we can.

I think we should show `module.exports = config;` instead of an empty function. maybe something like this:

`module.exports = ${createExports(configItems)}`

and then you can either show the function or just `config` depending on what is inside `configItems`

**Comment by jacekk** [comment]
@jakoblind Will do. Probably later today.

**Comment by jacekk** [comment]
@jakoblind Not the prettiest piece I've ever wrote ;) but please review again.

**Comment by jakoblind** [comment]
We're getting really close now :) These are my thoughts on how to make it a bit more readable: 

[patch.txt](https://github.com/jakoblind/webpack-autoconf/files/3700990/patch.txt)

Download the file and type `git apply patch.txt`

**Comment by jacekk** [comment]
@jakoblind Thx for the patch; looks better Though, could not resist to add couple empty lines ;)

**Comment by jakoblind** [comment]
awesome! thanks for your contribution!

**Pull request merged**
