### PR TITLE
#108 fixed htmlWebpackPlugin template issue

### PR DESCRIPTION
**Pull request by adardesign**

### CODE REVIEW

**Comment by jakoblind** [comment]
Thank you! I get an error when building, can you reproduce?

```[webpack-cli] Failed to load '/Users/jakoblind/Downloads/empty-project - 2021-07-07T190639.843/webpack.config.js' config
[webpack-cli] /Users/jakoblind/Downloads/empty-project - 2021-07-07T190639.843/webpack.config.js:38
                filename: \"index.html\",
                          ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/Users/jakoblind/Downloads/empty-project - 2021-07-07T190639.843/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/jakoblind/Downloads/empty-project - 2021-07-07T190639.843/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/Users/jakoblind/Downloads/empty-project - 2021-07-07T190639.843/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WebpackCLI.tryRequireThenImport (/Users/jakoblind/Downloads/empty-project - 2021-07-07T190639.843/node_modules/webpack-cli/lib/webpack-cli.js:32:22)
    at loadConfig (/Users/jakoblind/Downloads/empty-project - 2021-07-07T190639.843/node_modules/webpack-cli/lib/webpack-cli.js:1536:38)
npm ERR! code ELIFECYCLE
```

**Comment by jakoblind** [comment]
@adardesign Do you want to look into this? If you don't have time right now, I could fix it. Want to get this improvement shipped :)

**Review by adardesign — COMMENTED** [review]
Looks good

**Comment by jakoblind** [comment]
Thanks for your contribution!

**Pull request merged**
